---
# tasks file for exception

- include: deploy.yml

- name: Stopping "{{ application }}" ...
  service : name={{ application }} state=stopped

- name: Starting "{{ application }}" ...
  service: name={{ application }} state=started
